### ISSUE TITLE
Mais opções de pesquisas nos endpoints

### ISSUE THREAD

**Issue by dyorgio** [Secullum/PontoWebIntegracaoExternaExemplo#13]
Ola, gostaria de sugerir a inclusão da opção de pesquisar funcionário por Email (ou outros campos) pois hoje apenas PIS é suportado.

Porem faço a consulta nesse endpoint justamente para pegar o numero do pis, e possuo o e-mail.

Assim como essa melhoria, de modo geral mais endpoints poderiam ter mais opções de filtro.

**Comment by luizdasecullum** [comment]
Oi dyorgio desculpe o atraso, infelizmente não costumamos a olhar as issues aqui postadas.

Peço que direcione suas solicitações para nosso suporte técnico, assim será aberto um chamado para atender sua solicitação.
