### ISSUE TITLE
Normalizar o identificador do Banco

### ISSUE THREAD

**Issue by dyorgio** [Secullum/PontoWebIntegracaoExternaExemplo#14]
Ao consultar a lista de bancos o identificador vem com mascara (contendo o caractere '-').

Porem para conseguir usa-lo é necessário remover esse caractere, essa descoberta ocorre por tentativa e erro pois a documentação não menciona.

Sugiro então já trazer o valor sem mascara, aceitar com e sem mascara ou ajustar a documentação.

**Comment by luizdasecullum** [comment]
Oi dyorgio desculpe o atraso, infelizmente não costumamos a olhar as issues aqui postadas.

Peço que direcione suas solicitações para nosso suporte técnico, assim será aberto um chamado para atender sua solicitação.
