### ISSUE TITLE
Endpoint Batidas - Falta exemplo de retorno

### ISSUE THREAD

**Issue by dyorgio** [Secullum/PontoWebIntegracaoExternaExemplo#16]
A documentação não contem exemplo de retorno para o endpoint Batidas, nem mesmo a listagem de campos possíveis.

**Comment by luizdasecullum** [comment]
Oi dyorgio desculpe o atraso, infelizmente não costumamos a olhar as issues aqui postadas.

Peço que direcione suas solicitações para nosso suporte técnico, assim será aberto um chamado para atender sua solicitação.
