### ISSUE TITLE
Endpoint de Inconsistências Atrasos, Faltas, HE

### ISSUE THREAD

**Issue by KelvinSeverino** [Secullum/PontoWebIntegracaoExternaExemplo#17]
Olá, na documentação disponibilizada consta um endpoint de Batidas, porém não é mencionado um endpoint que traga as Inconsistências das batidas, como:
- Atrasos;
- Faltas;
- Horas Extras 60%,100%, Noturno.

Preciso destas informações para realizar integração em nosso sistema interno.

**Comment by luizdasecullum** [comment]
Ola Kelvin, em Batidas constam informações sobre os registros de ponto. Isso que vc está solicitando nós chamamos de Cálculos e não está disponível na nossa API de integração externa.

**Comment by KelvinSeverino** [comment]
Uma pena, pois são informações extremamente essenciais para nosso sistema interno, e como já consultei por outros meios, infelizmente não tem uma maneira de ter acesso aos "Cálculos" de maneira estruturada, seja por CSV, TXT. ou por um endpoint.

Se possível adicionem em um futura feature esse endpoint com as Inconsistências, pois será de grande valia, assim evita que sistemas terceiros que consumam a API precisem refazer toda a lógica para realizar os cálculos de inconsistências que a Secullum já possui.

Obrigado.

**Comment by luizdasecullum** [comment]
Ola Kelvin, deve estar acontecendo algum engano pois é possível sim acessar Cálculos por exportação de arquivos (CSV ou TXT). Usamos isso frequentemente com integrações de folhas de pagamento. Por favor, consulte mais informações neste link https://pontoweb.secullum.com.br/#/ajuda/relatorios-calculos na seção "Exportar". Se precisar de ajuda, entre em contato com nosso suporte técnico.

Também concordo com você em incluir os dados de Cálculos aqui na Integração Externa, isso pode ser feito através de uma solicitação do cliente junto ao suporte técnico para incluir isso no nosso banco de sugestões.
