### ISSUE TITLE
Integração com software EscalaJornadas

### ISSUE THREAD

**Issue by sergiojrdotnet** [Secullum/PontoWebIntegracaoExternaExemplo#2]
Gostaríamos de verificar os procedimentos para integração do Ponto Web com o software Escala App.
https://jornadas.escala.app/

O cliente irá criar as jornadas a partir deste sistema e elas deverão ser importadas diretamente para o Ponto Web através da API de integração.
http://escala-api-doc.s3-website-sa-east-1.amazonaws.com/#operation/get-eventos-escala

Além disso, o sistema deve enviar as marcações para a plataforma para conferência do cumprimento da escala.
http://escala-api-doc.s3-website-sa-east-1.amazonaws.com/#operation/post-marcacoes_de_ponto

**Comment by luizdasecullum** [comment]
Oi Sergio, nossa API está pronta para que você mesmo possa salvar/consultar dados dela. Se você quiser que nosso sistema consulte a sua API, será necessário implementarmos isso.

Por favor, peça para seu cliente entrar em contato com nosso revendedor para que possamos identifica-lo, e aí sim, iniciar um atendimento.

Luiz Eduardo Cezar
Desenvolvimento Secullum

**Comment by sergiojrdotnet** [comment]
Boa tarde Luiz! No caso, já sou representante da revenda **Reloponto Votuponto** em Votuporanga/SP.
Encaminhei a solicitação aqui conforme procedimento de atendimento em andamento no Octadesk #40299

**Comment by luizdasecullum** [comment]
Oi Sergio, acho que deve estar havendo algum engano. Vou pedir para que o Alexandre do nosso suporte entre em contato com você para retomar o atendimento.

Luiz Eduardo Cezar
Desenvolvimento Secullum
