### ISSUE TITLE
Limites de requisições/hora

### ISSUE THREAD

**Issue by Bernardo-Rufino** [Secullum/PontoWebIntegracaoExternaExemplo#27]
Gostaria de saber se há como aumentar o limite de requisições por hora (de 100 para 200 ou 300).

Estou enviando aqui porque já tentei em tudo quanto é lugar e não dão retorno...

Grato.

**Comment by luizdasecullum** [comment]
oi Bernardo, sim é possível, basta solicitar isso com a empresa que presta suporte técnico, pois que seja aberto um chamado com dados do cliente.

Você disse que já tentou "em tudo quanto é lugar", poderia me dizer quais contatos você tentou?

**Comment by Bernardo-Rufino** [comment]
Tentei em janeiro já, minha solicitação envolvia o endpoint /Calcular, onde é necessário passar o funcionário (PIS) e o mês, porém ficava limitado à um mês apenas. Precisava de um onde, ou eu poderia passar o funcionário e mais meses, ou então passar um intervalo e ele vir todos os funcionários em uma chamada...
Tentei conforme abaixo:

- https://www.secullum.com.br/pt/fale-conosco --> recebi informação que trabalham conforme revendas, e que deveria ver com eles;
- Verifiquei com a revenda, mas era um tópico mais técnico e ai não conseguiram resolver, e pediram pra entrar em contato com a Secullum novamente;
- Tentei o (51) 3205-1980, mas negaram me atender pois não atendem cliente final;
- Tentei com o Marcos, um contato de vocês que atende a revenda que atende a empresa que estou prestando serviço (ia verificar internamente, e nada de retorno);

No final cansamos, e deixamos para resolver outra hora... voltei com o projeto e agora, como ninguém respondeu sobre os endpoints, vamos ter que fazer várias requisições (nº funcionários X número de meses) para obter os dados que precisamos via API, e também diariamente (rodando do início do mês até a data atual para cada funcionário)... como passa de 100 funcionários, teria que quebrar a execução em várias horas que não nos atende... precisamos aumentar o limite de requisições.

Mais claro agora?

**Comment by luizdasecullum** [comment]
Quase 100%.

Sobre o procedimento de contato, todas as vezes que você entrou em contato com a Secullum foi orientado a procurar a revenda que presta o suporte técnico.... o que é correto.

Infelizmente o tal "Marcos" é que parou o processo.

Poderia me passar mais informações? Qual Marcos? Qual empresa?

Eu entro em contato com ele e explico a situação e ele vai destravar o processo.

**Comment by Bernardo-Rufino** [comment]
Conversei com a revenda e eles abriram um chamado com vocês, mas inicialmente quando foi falado com eles nada disso foi orientado por eles (somente agora por você).

Sobre o Marcos, a informação que tenho é que é um técnico da sua empresa, que atende a revenda que atende a empresa que eu atendo.

Na época falei com ele via whatsapp (não tenho mais o número).

**Comment by luizdasecullum** [comment]
Sim, eu vi que você é de Joinville então imagino que você esteja falando do Marcus da empresa Tecnoville (http://www.tecnoville.com.br/), nosso revendedor na sua cidade. Realmente ele está consultando nosso suporte agora para verificar o seu caso.

Por favor, siga o atendimento com ele e caso não conseguir, nos avise.
