### ISSUE TITLE
MotivoDemissao = null no cadastro de Funcionarios

### ISSUE THREAD

**Issue by jrvidotti** [Secullum/PontoWebIntegracaoExternaExemplo#9]
Ao consultar Funcionarios, o MotivoDemissao está vindo null:

```
    "MotivoDemissaoId": 5,
    "MotivoDemissao": null,
```

É esse o comportamento esperado?

**Comment by luizdasecullum** [comment]
Estas informações dependem do banco de dados que está sendo utilizado, por isso ressaltamos a importância de você contatar seu revendedor para que ele possa nos passar informações mais técnicas necessárias para avaliar o seu caso.
Utilize nossos canais de suporte para mais informações.
